name: now_vibes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    


  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  uuid: ^4.0.0
  hooks_riverpod: ^2.4.0
  font_awesome_flutter: ^10.5.0
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  image: ^4.1.0
  flutter_hooks: ^0.20.1
  collection: ^1.17.2
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.2
  lottie: ^2.6.0
  share_plus: ^4.5.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  